[package]
name = "puroro-protoc-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
ipc-channel = "0.18.0"
thiserror = "1.0.60"
puroro-plugin = { path = "../plugin", artifact = "bin:puroro-plugin" }
puroro = { path = "../puroro" }

[dev-dependencies]
tempfile = "3.10.1"
