[package]
name = "protoc-plugin-bin"
version = "0.1.0"
edition = "2021"
description = "An internal crate for protoc-plugin-by-closure crate."
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.83"
ipc-channel = "0.18.0"

[[bin]]
name = "protoc-plugin-bin"
path = "src/main.rs"
