[workspace]
members = [
    "puroro",
    "codegen",
    "inline",
    "plugin",
    "puroro-protobuf-compiled",
    "puroro-protobuf-compiler",
    "puroro-doc-samples",
    "update-puroro-protobuf",
    "tests",
    "tests-pb",
]