[workspace]
members = [
    "codegen",
    "protoc-plugin-bin",
    "protoc-plugin-by-closure",
    "puroro",
    "tests",
]
default-members = [
    "codegen",
    "protoc-plugin-bin",
    "puroro",
    "protoc-plugin-by-closure",
]
resolver = "2"
