[package]
name = "puroro-doc-samples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
puroro = { path = "../puroro" }

[build-dependencies]
puroro-plugin = { path = "../puroro-plugin" }

