[package]
name = "puroro-codegen"
version = "0.15.0"
edition = "2021"

[dependencies]
prettyplease = "0.2.19"
proc-macro2 = "1.0.81"
puroro = { path = "../puroro" }
quote = "1.0.36"
syn = "2.0.60"

[[bin]]
name = "puroro-plugin"
path = "src/main.rs"
