[package]
name = "puroro-plugin"
version = "0.1.0"
authors = ["Shohei Wada <pc@wada314.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
puroro = { git = "ssh://git@github.com/wada314/puroro", rev = "d29da0c" }
puroro-internal = { git = "ssh://git@github.com/wada314/puroro", rev = "d29da0c" }
askama = "0.10"
itertools = "0.10.0"
lazy_static = "1.4.0"
thiserror = "1.0.24"

[features]
puroro-nightly = []
default = ["puroro-nightly"]