[package]
name = "puroro-plugin"
version = "0.1.0"
authors = ["Shohei Wada <pc@wada314.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
puroro = { git = "ssh://git@github.com/wada314/puroro", rev = "26ad648bdefdd6493ac5afeff3448aa629560003" }
puroro-internal = { git = "ssh://git@github.com/wada314/puroro", rev = "26ad648bdefdd6493ac5afeff3448aa629560003" }
askama = "0.10"
itertools = "0.10.1"
lazy_static = "1.4.0"
thiserror = "1.0.25"
once_cell = "1.8.0"

[features]
puroro-nightly = []
default = ["puroro-nightly"]