[package]
name = "update-puroro-doc-samples"
version = "0.14.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protoc-bin-vendored = "3.1.0"
puroro-codegen = { path = "../codegen" }
