[package]
name = "puroro-inline"
version = "0.7.0"
edition = "2021"
license = "Apache-2.0"
description = "Google Protocol Buffer's compiler plugin implementation for puroro"
repository = "https://github.com/wada314/puroro"
documentation = "https://docs.rs/puroro/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
puroro-codegen = { path = "../codegen", version = "0.7.0" }
litrs = "0.2.3"
quote = "1.0"
proc-macro2 = "1.0"
protoc-bin-vendored = "3.0.0"
