[package]
name = "puroro"
version = "0.11.1"
authors = ["Shohei Wada <pc@wada314.jp>"]
edition = "2021"
license = "Apache-2.0"
description = "A Rust implementation of Google Protocol Buffer."
repository = "https://github.com/wada314/puroro"
readme = "../readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
either = "1.8"
bitvec = "1.0"
#stable_puroro = { package = "puroro", version = "0.11.1", optional = true }
#stable_puroro = { git = "https://github.com/wada314/puroro", branch = "master", package = "puroro", optional = true }
stable_puroro = { git = "https://github.com/wada314/puroro",  package = "puroro", rev = "ee81ed65cf5b73c3645f4e4e9c028633d8327a75", optional = true }

[features]
default = []
allocator_api = []
dev-for-protobuf-use-stable-puroro = ["stable_puroro"]
