[package]
name = "puroro"
version = "0.3.0"
authors = ["Shohei Wada <pc@wada314.jp>"]
edition = "2018"
license = "Apache-2.0"
description = "A Rust implementation of Google Protocol Buffer."
repository = "https://github.com/wada314/puroro"
readme = "../readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
num-traits = "0.2.14"
num-derive = "0.3.3"
either = "1.6.1"
once_cell = "1.8.0"
bumpalo = { version = "3.8.0", optional = true, features = ["collections", "boxed"] }
bitvec = "0.22.3"

[features]
default = ["puroro-bumpalo"]
puroro-bumpalo = ["bumpalo"]