[package]
name = "puroro"
version = "0.1.0"
authors = ["Shohei Wada <pc@wada314.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
num-traits = "0.2.14"
num-derive = "0.3.3"
either = "1.6.1"
bumpalo = { version = "3.7.0", features = ["collections", "boxed"], optional = true }
hashbrown = { version = "0.11", features = ["bumpalo"] }

[features]
puroro-nightly = []
puroro-bumpalo = ["bumpalo"]
default = ["puroro-nightly", "puroro-bumpalo"]