[package]
name = "puroro"
version = "0.1.0"
authors = ["Shohei Wada <pc@wada314.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"

[features]
nightly-specialization = []
nightly-gat = []
nightly-min-type-alias-impl-trait = []
nightly = ["nightly-specialization", "nightly-gat", "nightly-min-type-alias-impl-trait"]