[package]
name = "puroro"
version = "0.4.3"
authors = ["Shohei Wada <pc@wada314.jp>"]
edition = "2021"
license = "Apache-2.0"
description = "A Rust implementation of Google Protocol Buffer."
repository = "https://github.com/wada314/puroro"
readme = "../readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.34"
either = "1.6.1"
bitvec = "1.0.0"

[dev-dependencies]
puroro-doc-samples = { path = "../puroro-doc-samples" }

[features]