[package]
name = "puroro-protobuf-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
puroro = { version = "0.5.1" }
puroro-plugin = { version = "0.5.1" }