[package]
name = "puroro-protobuf-compiler"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
puroro = { path = "../puroro" }
puroro-codegen = { path = "../codegen" }